Add data read functionality
hursliza/Vastra pull request #1
Opened 2021-04-18 22:02 UTC by Qwebeck

2021-04-18 22:27 UTC, Qwebeck commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Nie było wcześniej w `.gitignore`, więc pewnie powinno być

2021-04-18 22:27 UTC, Qwebeck commented on .idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
IDE, nie ja

2021-04-18 22:27 UTC, Qwebeck commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
Jeśli dobrze pamiętam, to taka wersja JDK jest wymagana przez bazę danych której używamy. 
Ale nie jestem pewny, ponieważ bo zanim stanęło na tym rozwiązaniu które jest teraz próbowałem też kilka innych więc mogło zostać po tym.

Jeśli to jest problem - to sprawdzę, ale jeśli nie, to wolałbym nie tracić na to czasu

2021-04-18 22:27 UTC, Qwebeck commented on .idea/vcs.xml
> -    <mapping directory="$PROJECT_DIR$/.." vcs="Git" />
Zakładam, że pozostałość po folderze z wszystkimi projektami z mobilek :D

2021-04-18 22:27 UTC, Qwebeck commented on app/google-services.json
> +{
Plik konfiguracyjny do `Firebase`.

Pewnie lepiej nie wrzucać takich rzeczy na github, ale nie wiem jak najlepiej go ukryć. (rozwiązania które znam polegają na zrobieniu repa prywatnym)

 Ale w każdym razie myślę, że teraz to nie jest istotne

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/AndroidManifest.xml
> -        <activity
Usunałem, dlatego, że chciałem sprawdzić jak będzie wyglądać bez tego i zapomniałem przywrócić. 
(bo na `ProfileActivity` było dwa przyciski które wykonywały tę samą akcję)

Jeśli twoim zdaniem, lepiej tak jak było - to pisz, przywrócę

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/MainActivity.kt
> +val DEFAULT_USER_ID = "987654321";
Na razie jedyny użytkownik zapisany w naszej bazie :D 
Może jeśli będziemy mieli czas- to dodamy kolejnych.

Sama baza wygląda tak

![image](https://user-images.githubusercontent.com/21079319/115162427-c038e680-a0a3-11eb-9533-59d2b3fa4b6f.png)

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/data/Award.kt
> -package com.io.vastra.data
Zmieniłem ścieżkę

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/data/datasource/UserDataSource.kt
> +class UserDataSource(public val userId: String) {
Na razie zrobiłem `DataSource`, który udostępnia dane konkretnego użytkownika.

`DataSource` jest tworzony per `userId` i jest globalny dla całej aplikacji (to jest zapewniane w klasie `UserDataSourceProvider`, która jest niżej)

Zrobiłem tak, ponieważ:
1. Mniej połączeń z bazą danych. Aktualnie jest tylko jedno, ponieważ obiekt jest globalny, ale gdyby każdy fragment który z tego korzystał tworzył nowy dataSource, to było by zdecydowanie więcej.
2. Unikamy przekazywania `userId` do każdego fragmentu który chce w jakiś sposób korzystać z danych.

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/history/HistoryFeedFragment.kt
> +        return Time(0, 0, 0);
Trochę później dodam obsługę

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/data/datasource/UserDataSourceProvider.kt
> +class UserDataSourceProvider(userId: String) {
Nie wiem, ten singleton jest dobrym rozwiązaniem ale nie znalazłem lepszego, a on rozwiązuje te problemy o których pisałem wyżej.

Zdaję sobie sprawę, że później mogę pojawić się problemy z tym, że niektóre komponenty będą przechowywać uchwyt do `dataSource` z id starego użytkownika ponieważ teraz to jest zmienna, a nie `Observable`, ale na razie nie musimy się o to martwić z racji tego, że mamy tylko jednego user'a :D

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/history/historyItem/HistoryItemDetailsStatisticsFragment.kt
> +        calories.text = getString(R.string.calories, 875) //TODO count calories
Nie wiem czy my nie musimy usunąć kalorie. 
Bo szukałem dziś i mi się nie udało znaleźć jakiegoś api albo biblioteki do tego.
Ale też nie będę klamać, że specjalnie długo szukałem

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/history/historyItem/HistoryItemDetailsStatisticsFragment.kt
> +        calories.text = getString(R.string.calories, 875) //TODO count calories
Więc jeśli Ci uda się to znaleźć - to nie widzę żadnego problemu z tym, żeby to wykorzystać

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/history/historyItem/HistoryItemViewModel.kt
> +class HistoryItemViewModel(owner: LifecycleOwner, clickedIdx: Int): ViewModel()  {
Ten `ViewModel` jest potrzebny do tego, żeby współdzielić dane między `Fragmentami` które istnieją w ramach tego samego `Activity`

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/profile/ProfileViewModel.kt
> +class ProfileViewModel(viewOwner: LifecycleOwner, userId: String): ViewModel() {
Ten `ViewModel` nie ma specjalnego znaczenia (oprócz tego, że pozwala przecho)wac dane pod czas zmiany UI (np. rotacji))
Dodałem go ponieważ, myślałem, że będzie potrzebny, a kiedy okazało się że nie to nie chciałem tracić czas na to żeby go usuwać

2021-04-18 22:27 UTC, Qwebeck commented on app/src/main/java/com/io/vastra/running/details_fragment/DetailsFragment.kt
> +package com.io.vastra.running.details_fragment
Zmieniłem lokalizację tej klasy

2021-04-19 11:09 UTC, hursliza commented on app/src/main/AndroidManifest.xml
> -        <activity
Sprawdziam, nie działa bez tego (przynajmniej u mnie)
![image](https://user-images.githubusercontent.com/45465386/115227151-63bfe080-a110-11eb-9e60-8a265c8472f2.png)

2021-04-19 11:42 UTC, hursliza requested changes
Trzeba poprawić AndroidManifest.xml, zgodnie z dokumentacją Androida każdy komponent aplikacji musi być tam zadeklarowany.

2021-04-19 12:48 UTC, Qwebeck commented
> Trzeba poprawić AndroidManifest.xml, zgodnie z dokumentacją Androida każdy komponent aplikacji musi być tam zadeklarowany.

Racja.
Miałem pewność, że sprawdziłem czy działa. 

Poprawione

2021-04-19 13:17 UTC, hursliza approved these changes

2021-04-19 15:27 UTC, alicjak1519 approved these changes

2021-04-19 15:54 UTC, merged